# Generated by Django 4.0.6 on 2022-07-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='static/assets/img/books/', verbose_name='Imagen'),
        ),
    ]
