# Generated by Django 4.0.6 on 2022-07-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='creation_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
    ]
