# Generated by Django 4.0.6 on 2022-07-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_book_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
